const seed={projects:[{id:1,name:'Survival Skies',icon:'🎮',desc:'Story-driven survival adventure',progress:82,status:'In Development'},{id:2,name:'Pulse',icon:'💬',desc:'Modern communication platform',progress:67,status:'In Development'},{id:3,name:'Joel AI',icon:'🤖',desc:'Personal AI coding assistant',progress:40,status:'Planning'}],tasks:[{id:1,text:'Add ending cutscene',project:'Survival Skies',status:'doing',done:false},{id:2,text:'Fix tunnel collision',project:'Survival Skies',status:'todo',done:false},{id:3,text:'Build project dashboard',project:'ProjectOS',status:'doing',done:false},{id:4,text:'Polish mobile layout',project:'Pulse',status:'done',done:true},{id:5,text:'Connect GitHub projects',project:'ProjectOS',status:'todo',done:false}],ideas:[{id:1,title:'Musician collaboration platform',icon:'🎵',tag:'Music',body:'A place where musicians can find people to make music with.'},{id:2,title:'AI game generator',icon:'🎮',tag:'Games',body:'Describe a game and generate a playable prototype.'},{id:3,title:'SkillSwap',icon:'🤝',tag:'Community',body:'Trade skills with other creators instead of paying.'}]};
let data=JSON.parse(localStorage.getItem('projectos-data')||'null')||seed;const save=()=>localStorage.setItem('projectos-data',JSON.stringify(data));
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function render(){renderStats();renderProjects();renderTasks();renderIdeas();save()}
function renderStats(){const done=data.tasks.filter(t=>t.done).length;$('#stats').innerHTML=`<div class="stat"><div class="label">ACTIVE PROJECTS</div><div class="value">${data.projects.length}</div></div><div class="stat"><div class="label">TASKS COMPLETE</div><div class="value">${done}</div></div><div class="stat"><div class="label">OPEN TASKS</div><div class="value">${data.tasks.length-done}</div></div><div class="stat"><div class="label">IDEAS CAPTURED</div><div class="value">${data.ideas.length}</div></div>`}
function projectCard(p){return `<article class="project-card"><div class="project-top"><div class="project-icon">${p.icon}</div><span class="status">${p.status}</span></div><h4>${esc(p.name)}</h4><div class="muted">${esc(p.desc)}</div><div class="progress"><i style="width:${p.progress}%"></i></div><div class="progress-meta"><span>Progress</span><b>${p.progress}%</b></div></article>`}
function renderProjects(){$('#dashboardProjects').innerHTML=data.projects.slice(0,3).map(projectCard).join('');$('#allProjects').innerHTML=data.projects.map(projectCard).join('')||empty('No projects yet. Create your first one!')}
function taskRow(t){return `<label class="task-row ${t.done?'done':''}"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span>${esc(t.text)}</span><small class="task-project">${esc(t.project)}</small></label>`}
function renderTasks(){const open=data.tasks.filter(t=>!t.done);$('#dashboardTasks').innerHTML=(open.length?open.slice(0,4).map(taskRow).join(''):empty('You’re all caught up 🎉'));const cols=[['todo','TODO'],['doing','DOING'],['review','REVIEW'],['done','DONE']];$('#kanban').innerHTML=cols.map(([key,label])=>`<div class="kanban-column"><div class="column-title"><span>${label}</span><span>${data.tasks.filter(t=>key==='done'?t.done:t.status===key&&!t.done).length}</span></div>${data.tasks.filter(t=>key==='done'?t.done:t.status===key&&!t.done).map(t=>`<div class="kanban-task">${esc(t.text)}<small>${esc(t.project)}</small></div>`).join('')}</div>`).join('')}
function renderIdeas(){$('#ideasGrid').innerHTML=data.ideas.map(i=>`<article class="idea-card"><div class="idea-icon">${i.icon}</div><h4>${esc(i.title)}</h4><div class="muted">${esc(i.body)}</div><span class="tag">${esc(i.tag)}</span></article>`).join('')||empty('Your idea vault is empty. Capture something!')}
function empty(text){return `<div class="task-row"><span>${text}</span></div>`}function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function show(view){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+view).classList.add('active-view');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const titles={dashboard:'Good afternoon, Joel 👋',projects:'Projects',tasks:'Tasks',ideas:'Idea Vault'};$('#page-title').innerHTML=titles[view]||'ProjectOS';window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(n=>n.onclick=()=>show(n.dataset.view));$$('[data-view-target]').forEach(n=>n.onclick=()=>show(n.dataset.viewTarget));
function openModal(type){const configs={project:{title:'Create a project',fields:`<div class="field"><label>PROJECT NAME</label><input id="f-name" placeholder="e.g. Survival Skies"></div><div class="field"><label>DESCRIPTION</label><input id="f-desc" placeholder="What are you building?"></div><div class="field"><label>ICON</label><input id="f-icon" value="🚀" maxlength="2"></div>`},task:{title:'Create a task',fields:`<div class="field"><label>TASK</label><input id="f-name" placeholder="What needs to happen?"></div><div class="field"><label>PROJECT</label><input id="f-desc" placeholder="Project name"></div>`},idea:{title:'Capture an idea',fields:`<div class="field"><label>IDEA</label><input id="f-name" placeholder="What's the idea?"></div><div class="field"><label>DESCRIPTION</label><textarea id="f-desc" placeholder="Write down the details..."></textarea></div><div class="field"><label>CATEGORY</label><input id="f-icon" value="💡" placeholder="Emoji"></div>`}};const c=configs[type];$('#modal').innerHTML=`<h3>${c.title}</h3>${c.fields}<div class="modal-actions"><button class="cancel" id="cancel">Cancel</button><button class="primary" id="create">Create</button></div>`;$('#modalBackdrop').classList.add('open');$('#cancel').onclick=closeModal;$('#create').onclick=()=>{const name=$('#f-name').value.trim();if(!name)return;const desc=$('#f-desc')?.value.trim()||'';if(type==='project')data.projects.unshift({id:Date.now(),name,desc:desc||'New creative project',icon:$('#f-icon').value||'🚀',progress:0,status:'Planning'});if(type==='task')data.tasks.unshift({id:Date.now(),text:name,project:desc||'General',status:'todo',done:false});if(type==='idea')data.ideas.unshift({id:Date.now(),title:name,body:desc||'A new idea worth exploring.',icon:$('#f-icon').value||'💡',tag:'New'});closeModal();render()}}
function closeModal(){$('#modalBackdrop').classList.remove('open')}$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('#newProject').onclick=()=>openModal('project');$('#newProjectHero').onclick=()=>openModal('project');$('#newTask').onclick=()=>openModal('task');$('#newIdea').onclick=()=>openModal('idea');
document.addEventListener('change',e=>{if(e.target.matches('[data-task]')){const t=data.tasks.find(x=>x.id==e.target.dataset.task);if(t){t.done=e.target.checked;t.status=e.target.checked?'done':'todo';render()}}});render();