const seed={projects:[{name:'Survival Skies',desc:'Story-driven survival game',progress:82,status:'In Development'},{name:'Pulse',desc:'Messaging and communication platform',progress:67,status:'In Development'},{name:'PVP',desc:'Fast-paced multiplayer combat',progress:45,status:'Testing'}],tasks:[{text:'Finish Survival Skies ending',done:false,project:'Survival Skies'},{text:'Polish Pulse messaging',done:false,project:'Pulse'},{text:'Balance PVP weapons',done:true,project:'PVP'}],ideas:[{name:'Creator collaboration platform',desc:'A place for creators to find collaborators'},{name:'GameForge',desc:'Build simple games without coding'}]};
let data=JSON.parse(localStorage.getItem('projectos-data')||'null')||seed;function save(){localStorage.setItem('projectos-data',JSON.stringify(data))}const content=document.getElementById('content'),title=document.getElementById('title');
const kinetic=document.getElementById('kinetic-grid');const glow=document.createElement('div');glow.className='grid-glow';kinetic.appendChild(glow);let tx=0,ty=0;
function moveKinetic(e){const x=e.clientX/window.innerWidth-.5,y=e.clientY/window.innerHeight-.5;tx=x*34;ty=y*26;glow.style.transform=`translate(${e.clientX}px,${e.clientY}px) translate(-50%,-50%)`;document.documentElement.style.setProperty('--kinetic-x',`${x*18}px`);document.documentElement.style.setProperty('--kinetic-y',`${y*14}px`)}
window.addEventListener('pointermove',moveKinetic,{passive:true});window.addEventListener('pointerleave',()=>{tx=ty=0;document.documentElement.style.setProperty('--kinetic-x','0px');document.documentElement.style.setProperty('--kinetic-y','0px')});function animateGrid(){kinetic.style.setProperty('--mx',`${tx}px`);kinetic.style.setProperty('--my',`${ty}px`);requestAnimationFrame(animateGrid)}animateGrid();
function dashboard(){title.textContent='Dashboard';content.innerHTML=`<div class="hero"><h2>Build. Organize. Ship. 🚀</h2><div class="muted">Welcome to ProjectOS — your workspace for everything you create.</div></div><div class="stats"><div class="stat"><small>Projects</small><strong>${data.projects.length}</strong></div><div class="stat"><small>Tasks</small><strong>${data.tasks.length}</strong></div><div class="stat"><small>Completed</small><strong>${data.tasks.filter(x=>x.done).length}</strong></div><div class="stat"><small>Ideas</small><strong>${data.ideas.length}</strong></div></div><div class="section-head"><h3>Active Projects</h3><button class="primary" onclick="openModal('project')">+ New Project</button></div><div class="grid">${data.projects.map(p=>projectCard(p)).join('')}</div>`}
function projectCard(p){return `<div class="card project"><span class="tag">${p.status}</span><h3>${p.name}</h3><div class="muted">${p.desc}</div><div class="progress"><i style="width:${p.progress}%"></i></div><small class="muted">${p.progress}% complete</small></div>`}
function projects(){title.textContent='Projects';content.innerHTML=`<div class="section-head"><h3>All Projects</h3><button class="primary" onclick="openModal('project')">+ New Project</button></div><div class="grid">${data.projects.map(projectCard).join('')}</div>`}
function tasks(){title.textContent='Tasks';content.innerHTML=`<div class="section-head"><h3>Task Board</h3></div><div class="list">${data.tasks.map((t,i)=>`<div class="card task"><button class="check" onclick="toggleTask(${i})">${t.done?'✓':''}</button><div style="flex:1"><strong style="${t.done?'text-decoration:line-through;opacity:.5':''}">${t.text}</strong><div class="muted">${t.project}</div></div></div>`).join('')}</div>`}
function ideas(){title.textContent='Idea Vault';content.innerHTML=`<div class="section-head"><h3>Your ideas</h3><button class="primary" onclick="openModal('idea')">+ New Idea</button></div><div class="grid">${data.ideas.map(i=>`<div class="card"><span class="tag">IDEA</span><h3>${i.name}</h3><div class="muted">${i.desc}</div></div>`).join('')}</div>`}
function toggleTask(i){data.tasks[i].done=!data.tasks[i].done;save();tasks()}function openModal(type){document.getElementById('modal').classList.remove('hidden');document.getElementById('modalTitle').textContent=type==='project'?'New project':'New idea';document.getElementById('saveModal').dataset.type=type;document.getElementById('nameInput').value='';document.getElementById('descInput').value=''}document.getElementById('closeModal').onclick=()=>document.getElementById('modal').classList.add('hidden');document.getElementById('saveModal').onclick=()=>{const n=document.getElementById('nameInput').value.trim(),d=document.getElementById('descInput').value.trim();if(!n)return;if(document.getElementById('saveModal').dataset.type==='project')data.projects.push({name:n,desc:d||'New project',progress:0,status:'Planning'});else data.ideas.push({name:n,desc:d||'New idea'});save();document.getElementById('modal').classList.add('hidden');render(location.hash.slice(1)||'dashboard')};
function render(view){document.querySelectorAll('.nav[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));({dashboard,projects,tasks,ideas}[view]||dashboard)()}document.querySelectorAll('.nav[data-view]').forEach(b=>b.onclick=()=>render(b.dataset.view));render('dashboard');
